# Generated by Django 4.2.5 on 2023-09-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_promoters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('discription', models.TextField()),
                ('faq_type', models.CharField(choices=[('existing_deposit', 'Existing Deposit'), ('new_deposit', 'New Deposit '), ('rent_tracking', 'Rent Tracking')], max_length=255)),
            ],
        ),
    ]
