# Generated by Django 4.2.5 on 2023-09-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_testimonial_image_alter_faq_faq_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='faq_type',
            field=models.CharField(choices=[('rent_tracking', 'Rent Tracking'), ('existing_deposit', 'Existing Deposit'), ('new_deposit', 'New Deposit ')], max_length=255),
        ),
    ]
