# Generated by Django 4.2.5 on 2023-09-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_subscribe_alter_faq_faq_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='faq_type',
            field=models.CharField(choices=[('new_deposit', 'New Deposit '), ('rent_tracking', 'Rent Tracking'), ('existing_deposit', 'Existing Deposit')], max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
