# Generated by Django 4.2.5 on 2023-09-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_faq_faq_type_alter_testimonial_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='faq_type',
            field=models.CharField(choices=[('existing_deposit', 'Existing Deposit'), ('new_deposit', 'New Deposit '), ('rent_tracking', 'Rent Tracking')], max_length=255),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
