# Generated by Django 4.2.5 on 2023-09-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_manufacturer_alter_faq_faq_type_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='faq',
            name='faq_type',
            field=models.CharField(choices=[('rent_tracking', 'Rent Tracking'), ('new_deposit', 'New Deposit '), ('existing_deposit', 'Existing Deposit')], max_length=255),
        ),
    ]
