# Generated by Django 4.2.5 on 2023-09-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_manu_alter_faq_faq_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='faq_type',
            field=models.CharField(choices=[('existing_deposit', 'Existing Deposit'), ('new_deposit', 'New Deposit '), ('rent_tracking', 'Rent Tracking')], max_length=255),
        ),
    ]
