# Generated by Django 4.2.5 on 2023-09-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_faq_faq_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='faq_type',
            field=models.CharField(choices=[('new_deposit', 'New Deposit '), ('rent_tracking', 'Rent Tracking'), ('existing_deposit', 'Existing Deposit')], max_length=255),
        ),
        migrations.RenameModel(
            old_name='Manu',
            new_name='StudentGroup',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('group', models.ManyToManyField(to='web.studentgroup')),
            ],
        ),
    ]
